### ISSUE TITLE
program gives RTS error when I build it locally using nix-build or nix-shell + cabal build

### ISSUE THREAD

**Issue by jhartzell42** [obsidiansystems/seven-guis-vty#1]
From a fresh checkout and `nix-build`, I get the following error when I try to run the binary:
```
[jim@palatinate:~/hobby/seven-guis-vty]$ result/bin/seven-guis-vty-counter
seven-guis-vty-counter: user error (RTS doesn't support multiple OS threads (use ghc -threaded when linking))
```

I get the same error when using `nix-shell` and `cabal build` to build the binary.

**Comment by ali-abrar** [comment]
Thanks Jimmy. Fixed in 91ebb274119c324902ef7b0f49a378f9730d19b7
